package com.example.recyclerviewapidatabindingpractice.view.recyclerview

import androidx.recyclerview.widget.RecyclerView
import com.example.recyclerviewapidatabindingpractice.databinding.CharactersRecyclerItemBinding

class CharacterRecyclerViewHolder(val binding: CharactersRecyclerItemBinding) : RecyclerView.ViewHolder(binding.root)